---
site_name: Pacifica Internet Technology Package
docs_dir: docs
# use_directory_urls: false
theme:
  name: readthedocs
# These extensions recommended by
# https://squidfunk.github.io/mkdocs-material/reference/images/
markdown_extensions:
  - attr_list
  - md_in_html
plugins:
  - glightbox
